import { supabase } from '@/lib/supabase';
import type { Category, Venue } from '@/types';
const publicFields = 'id,name,slug,category_id,address_line,postal_code,city,latitude,longitude,description,queer_context,website_url,instagram_url,price_level,published_at';
export async function listVenues({ query = '', categoryId }: { query?: string; categoryId?: number | null } = {}) { let request = supabase.from('published_venues').select(publicFields).order('published_at', { ascending: false }).limit(80); if (query.trim()) request = request.or(`name.ilike.%${query.trim()}%,city.ilike.%${query.trim()}%,address_line.ilike.%${query.trim()}%`); if (categoryId) request = request.eq('category_id', categoryId); const { data, error } = await request; if (error) throw error; return (data ?? []) as Venue[]; }
export async function getVenue(id: string) { const { data, error } = await supabase.from('published_venues').select(publicFields).eq('id', id).single(); if (error) throw error; return data as Venue; }
export async function listCategories() { const { data, error } = await supabase.from('venue_categories').select('id,slug,label,icon_name').eq('is_active', true).order('sort_order'); if (error) throw error; return (data ?? []) as Category[]; }
export async function listNearby(lat: number, lng: number, radiusMeters = 500) { const { data, error } = await supabase.rpc('nearby_venues', { user_lat: lat, user_lng: lng, radius_meters: radiusMeters, result_limit: 30, category_slug: null, required_tag_slugs: [] }); if (error) throw error; return (data ?? []) as Venue[]; }
export type VenueDraft = { name: string; category_id: number | null; address_line: string; postal_code?: string; city: string; latitude: number; longitude: number; description?: string; queer_context?: string; };
export async function submitVenue(input: VenueDraft) { const { data: auth } = await supabase.auth.getUser(); if (!auth.user) throw new Error('Connectez-vous pour ajouter un spot.'); const slugBase = input.name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''); const slug = `${slugBase || 'spot'}-${Date.now().toString(36)}`; const { data, error } = await supabase.from('venues').insert({ owner_user_id: auth.user.id, category_id: input.category_id, name: input.name.trim(), slug, description: input.description?.trim() || null, queer_context: input.queer_context?.trim() || null, address_line: input.address_line.trim(), postal_code: input.postal_code?.trim() || null, city: input.city.trim() || 'Paris', country_code: 'FR', latitude: input.latitude, longitude: input.longitude, status: 'draft' }).select('id').single(); if (error) throw error; const finalize = await supabase.from('venues').update({ status: 'pending_review' }).eq('id', data.id); if (finalize.error) throw finalize.error; return data.id as string; }
