import { useEffect, useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, View } from 'react-native';
import * as Location from 'expo-location';
import { router } from 'expo-router';
import { BrandHeader } from '@/components/BrandHeader';
import { Button, Input, Pill, Screen } from '@/components/ui';
import { VenueCard } from '@/components/VenueCard';
import { listCategories, listNearby, submitVenue } from '@/services/venues';
import type { Category, Venue } from '@/types';
import { useAuth } from '@/contexts/AuthContext';
import { colors, radius } from '@/theme';
export default function AddScreen() {
  const { user } = useAuth();
  const [categories, setCategories] = useState<Category[]>([]); const [nearby, setNearby] = useState<Venue[]>([]); const [location, setLocation] = useState<{ latitude: number; longitude: number } | null>(null);
  const [name, setName] = useState(''); const [address, setAddress] = useState(''); const [postal, setPostal] = useState(''); const [city, setCity] = useState('Paris'); const [description, setDescription] = useState(''); const [context, setContext] = useState(''); const [categoryId, setCategoryId] = useState<number | null>(null); const [sending, setSending] = useState(false);
  useEffect(() => { void listCategories().then(setCategories).catch(() => setCategories([])); }, []);
  const locate = async () => { const permission = await Location.requestForegroundPermissionsAsync(); if (permission.status !== 'granted') { Alert.alert('Localisation', 'Autorise la localisation pour vérifier les établissements dans un rayon de 500 m.'); return; } const current = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.High }); const coords = { latitude: current.coords.latitude, longitude: current.coords.longitude }; setLocation(coords); setNearby(await listNearby(coords.latitude, coords.longitude, 500).catch(() => [])); const reversed = await Location.reverseGeocodeAsync(coords).catch(() => []); const reverse = reversed[0]; if (reverse) { setAddress([reverse.streetNumber, reverse.street].filter(Boolean).join(' ')); setPostal(reverse.postalCode ?? ''); setCity(reverse.city ?? reverse.district ?? 'Paris'); } };
  const submit = async () => { if (!user) { router.push('/auth'); return; } if (!location) { Alert.alert('Localisation requise', 'Utilise « Me localiser » afin de vérifier les doublons dans les 500 m.'); return; } if (!name.trim() || !address.trim()) { Alert.alert('Informations manquantes', 'Ajoute au minimum le nom et l’adresse du lieu.'); return; } setSending(true); try { await submitVenue({ name, category_id: categoryId, address_line: address, postal_code: postal, city, latitude: location.latitude, longitude: location.longitude, description, queer_context: context }); Alert.alert('Merci ✦', 'Le spot a été envoyé à la modération. Il ne sera publié qu’après validation.'); setName(''); setDescription(''); setContext(''); } catch (error: any) { Alert.alert('Envoi impossible', error?.message ?? 'Réessaie plus tard.'); } finally { setSending(false); } };
  return <Screen><ScrollView contentContainerStyle={styles.container}><BrandHeader /><Text style={styles.kicker}>AJOUTER UN SPOT</Text><Text style={styles.title}>Partage une adresse utile à la communauté.</Text><View style={styles.locationCard}><Text style={styles.locationTitle}>Vérification autour de toi · 500 m</Text><Text style={styles.locationText}>On regarde d’abord si le lieu existe déjà pour limiter les doublons.</Text><View style={{ marginTop: 12 }}><Button label={location ? 'Actualiser ma position' : 'Me localiser'} onPress={() => void locate()} /></View></View>{location && <Text style={styles.coords}>Position détectée : {location.latitude.toFixed(5)}, {location.longitude.toFixed(5)}</Text>}{nearby.length > 0 && <View style={{ gap: 8, marginBottom: 18 }}><Text style={styles.sectionTitle}>Déjà présents dans les 500 m</Text>{nearby.slice(0, 5).map((venue) => <VenueCard key={venue.id} venue={venue} />)}</View>}<View style={{ gap: 10 }}><Input value={name} onChangeText={setName} placeholder="Nom de l’établissement" /><ScrollView horizontal showsHorizontalScrollIndicator={false}>{categories.map((category) => <Pill key={category.id} label={category.label} active={categoryId === category.id} onPress={() => setCategoryId(category.id)} />)}</ScrollView><Input value={address} onChangeText={setAddress} placeholder="Adresse" /><View style={{ flexDirection: 'row', gap: 8 }}><Input value={postal} onChangeText={setPostal} placeholder="Code postal" style={{ flex: 1 }} /><Input value={city} onChangeText={setCity} placeholder="Ville" style={{ flex: 1 }} /></View><Input value={description} onChangeText={setDescription} placeholder="Pourquoi recommandes-tu ce lieu ?" multiline /><Input value={context} onChangeText={setContext} placeholder="Contexte queer / inclusif observé (facultatif)" multiline /><Button label={sending ? 'Envoi…' : user ? 'Envoyer à la modération' : 'Se connecter pour envoyer'} disabled={sending} onPress={() => void submit()} /></View><Text style={styles.note}>Une contribution ne garantit jamais la sécurité en temps réel. Les informations sensibles et signalements graves restent confidentiels.</Text></ScrollView></Screen>;
}
const styles = StyleSheet.create({ container: { paddingHorizontal: 18, paddingTop: 10, paddingBottom: 120 }, kicker: { color: colors.mint, fontWeight: '900', letterSpacing: 2 }, title: { color: colors.ivory, fontSize: 30, lineHeight: 33, fontWeight: '900', marginTop: 8, marginBottom: 16 }, locationCard: { backgroundColor: colors.panel2, borderRadius: radius.lg, padding: 16, borderWidth: 1, borderColor: colors.purple }, locationTitle: { color: colors.lime, fontWeight: '900' }, locationText: { color: colors.muted, lineHeight: 19, marginTop: 4 }, coords: { color: colors.mint, marginVertical: 10, fontSize: 12 }, sectionTitle: { color: colors.ivory, fontWeight: '900', marginTop: 6 }, note: { color: colors.muted, lineHeight: 18, fontSize: 12, marginTop: 18 } });
