import type { PropsWithChildren } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View, type TextInputProps } from 'react-native';
import { colors, radius } from '@/theme';
export function Screen({ children }: PropsWithChildren) { return <View style={styles.screen}>{children}</View>; }
export function Card({ children }: PropsWithChildren) { return <View style={styles.card}>{children}</View>; }
export function Button({ label, onPress, variant = 'primary', disabled = false }: { label: string; onPress: () => void; variant?: 'primary' | 'secondary' | 'danger'; disabled?: boolean }) { return <Pressable disabled={disabled} onPress={onPress} style={[styles.button, variant === 'secondary' && styles.buttonSecondary, variant === 'danger' && styles.buttonDanger, disabled && { opacity: 0.45 }]}><Text style={[styles.buttonText, variant === 'secondary' && { color: colors.ivory }]}>{label}</Text></Pressable>; }
export function Input(props: TextInputProps) { return <TextInput placeholderTextColor={colors.muted} {...props} style={[styles.input, props.multiline && { minHeight: 96, textAlignVertical: 'top' }, props.style]} />; }
export function Pill({ label, active, onPress }: { label: string; active?: boolean; onPress?: () => void }) { return <Pressable onPress={onPress} style={[styles.pill, active && styles.pillActive]}><Text style={[styles.pillText, active && { color: colors.night }]}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.night }, card: { backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.line, borderRadius: radius.md, padding: 16 }, button: { minHeight: 48, borderRadius: radius.pill, backgroundColor: colors.fuchsia, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18 }, buttonSecondary: { backgroundColor: colors.panel2, borderWidth: 1, borderColor: colors.line }, buttonDanger: { backgroundColor: colors.danger }, buttonText: { color: colors.white, fontWeight: '900', fontSize: 15 }, input: { minHeight: 48, borderRadius: radius.md, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel, color: colors.ivory, paddingHorizontal: 14, paddingVertical: 12, fontSize: 16 }, pill: { borderRadius: radius.pill, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel, paddingHorizontal: 14, paddingVertical: 9, marginRight: 8 }, pillActive: { backgroundColor: colors.mint, borderColor: colors.mint }, pillText: { color: colors.ivory, fontWeight: '800', fontSize: 13 } });
